from tkinter import *
from tkcalendar import DateEntry
def preview():
    Label(appointment,text='Date:'+l14.get()).grid(row=13,column=1)
    Label(appointment,text='Name:'+e2.get()+e3.get()).grid(row=14,column=1)
    Label(appointment,text='DR:'+clicked.get()).grid(row=16,column=2)
    Label(appointment,text='gender: '+e20.get()+e21.get()+e22.get()).grid(row=15,column=1)
appointment=Tk()
appointment.title("CONSULTING FORM")
appointment.geometry("800x600")
appointment.config(bg='#C292DE')
options=["Dr.ASWIN MBBS(CARDIOLOGIST)","Dr.NIZAM MBBS MD(ENT)","Dr.LINCY MBBS(ORTHO)","Dr.NADIR FRCS(NUERO)","Dr.SRILAKSHMI(GYNECOLOGIST)","Dr.ASHWIN KODUVATHARA MBBS(GENERAL)"]
clicked=StringVar()
v=IntVar()
clicked.set("Dr.ASHWIN KODUVATHARA MBBS(GENERAL)")
l1=Label(appointment,text="DATE :",bg='#C292DE').grid(row=1,column=20)
l12=Label(appointment,text="CONSULTING FORM",font="70",bg='#C292DE').grid(row=0,column=2)
l2=Label(appointment,text="FIRST NAME :",bg='#C292DE').grid(row=3)
l3=Label(appointment,text="LAST NAME :",bg='#C292DE').grid(row=3,column=2)
l4=Label(appointment,text="ADDRESS :",bg='#C292DE').grid(row=4)
l5=Label(appointment,text="GENDER :",bg='#C292DE').grid(row=5)
l6=Label(appointment,text="PHONE NUMBER :",bg='#C292DE').grid(row=6)
l7=Label(appointment,text="E-MAIL :",bg='#C292DE').grid(row=7)
l8=Label(appointment,text="AGE :",bg='#C292DE').grid(row=8)
l9=Label(appointment,text="WEIGHT(Kg) :",bg='#C292DE').grid(row=9)
l10=Label(appointment,text="HEIGHT(cm) :",bg='#C292DE').grid(row=10)
l11=Label(appointment,text="CONSULTING DOCTOR :",bg='#C292DE').grid(row=11)
l14=DateEntry(appointment,text="DATE :",bg='#C292DE')
l14.grid(row=1,column=21)
e2=Entry(appointment)
e2.grid(row=3,column=1)
e3=Entry(appointment)
e3.grid(row=3,column=3)
e4=Text(appointment,height=3,width=15).grid(row=4,column=1)
e20=Radiobutton(appointment,text='Male',variable=v,value=1,bg='#C292DE')
e20.grid(row=5,column=1)
e21=Radiobutton(appointment,text='Female',variable=v,value=2,bg='#C292DE')
e21.grid(row=5,column=2)
e22=Radiobutton(appointment,text='Others',variable=v,value=3,bg='#C292DE')
e22.grid(row=5,column=3)
e8=Entry(appointment).grid(row=6,column=1)
e9=Entry(appointment).grid(row=7,column=1)
e10=Entry(appointment).grid(row=8,column=1)
e11=Entry(appointment).grid(row=9,column=1)
e12=Entry(appointment).grid(row=10,column=1)
e13=OptionMenu(appointment,clicked,*options)
e13.grid(row=11,column=1)
btn=Button(appointment,text='Submit',command=preview).grid(row=12,column=2)
mainloop()